#Sprint 9
VVish1337/java-filmorate pull request #3
Opened 2022-06-17 12:11 UTC by VVish1337

2022-06-17 21:16 UTC, Fleaman777 requested changes

2022-06-17 21:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(long id, String name, String description, LocalDate releaseDate, int duration) {
можно оставить аннотацию @AllArgsConstructor, просто links сразу проинициализировать 

аналагично в ЮзерСервисе

2022-06-17 21:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryUserStorage userStorage;
поля должны быть private

2022-06-17 21:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            filmStorage.getFilmsMap().get(filmId).getLikes().add(userId);
в ФильмСторедже можно сделать метод getFilmById(id) и использовать его вместо filmStorage.getFilmsMap().get(filmId)

аналагично и в юзер сервисе

2022-06-17 21:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Comparator<Film> comparator = Comparator.comparingLong(a -> a.getLikes().size());
для улучшения разделения ответственности, компаратор можно вынести в отдельный метод,
или если его не исользовать, то можно классом Film симплементировать интерфейс Comparable

2022-06-17 21:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return sortedListFilms.stream().limit(count).collect(Collectors.toList());
стримы хорошо воспринимать, если они отформотированы в стим стиле :)

2022-06-17 21:16 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
можешь попробовать логику выполнения с листами/сетами вынести с тримы, 
если получится, то должно выглядеть очень хорош

можно считать это задание под звездочкой 

в фильмСервисе аналагично

2022-06-17 21:16 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//    }
что бы не комментировать тесты, можно использовать аннотацю @Disabled

2022-06-18 17:15 UTC, VVish1337 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//    }
Я добавил @disabled,но что то тесты на гитхабе не прошло я добалял на весь класс или нужно было на каждый тест повесить?

2022-06-19 18:28 UTC, Fleaman777 requested changes

2022-06-19 18:28 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorage.getFilmsMap().get(filmId);
хорошо было бы сделать метод getFilmById(id) в фильмСторедже, 
а здесь в сервисе метод getFilmById(id) уже бы использовал метод стореджа, и проверял бы, если фильм null, то эксепшен, если нет, то возвращает фильм
 
аналагично можно сделать и c юзером

2022-06-19 18:28 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film getById(long filmId) {
лучше переименовать в более привычное getFilmById, так код будет проще восприниматься

2022-06-19 18:28 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                    .collect(Collectors.toCollection(ArrayList<User>::new));
отличный получился стрим, 
только у него немного форматтинг поехал

2022-06-21 07:32 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//    }
ага, надо было на каждый тест повесить

чем комментирование всех тестов не очень хорошо, 
когда разработку будут вести несолько человек, после того как закомментировать весь код, потом закоммитеть-запушить, нельзя будет посмотреть нормальную историю изменений в тестах, т.к. тот этот  коммит который был с комментариями, всю историю перезатрет

2022-07-07 13:04 UTC, merged